a=float(input("Какая длинна прямоугольника(а)?"))
b=float(input("Какая ширина прямоугольника(b)?"))
perimetr=float((a+b)*2)
area=float(a*b)
print("-------------")
print("Периметр",perimetr)
print("Площядь",area)
